name = "FlywheelSMP"
author = "Kosmic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a28992fa3483f2f3dd09a1274a3eeb607ce2d4126ff102e317e87a686ffff3c"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
