name = "FlywheelSMP"
author = "Kosmic"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a13de485c84dec311ea5280285f5b4471e422b0edac5f17c821f794cf8342c73"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
