name = "FlywheelSMP"
author = "Kosmic"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "012b5d13b6fb89746b2a8792dd938f47a8f362a17eeb30f3c76096a9f6d8cc68"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
