name = "FlywheelSMP"
author = "Kosmic"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d13c5733c9caf0389ae5c42b68285ed325f4bce4b9b9c574cc1862f5ff331ce"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
