name = "FlywheelSeason2"
author = "Kosmic"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d800495e15c505cabbd631b837ea5e9f66e0b5160ed60f5562bc8009f42b583f"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
