name = "FlywheelSeason2"
author = "Kosmic"
version = "1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1879088a72ce697b59b04304b964e4107e2d53b6fe73a3de94acbae4445a7a00"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
