name = "FlywheelSMP"
author = "Kosmic"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "830a13621d07f40e55c79488bdb857101df80cbecc2e0ff71ed73f7968966ba6"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
