name = "FlywheelSMP"
author = "Kosmic"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ee17ce2e85c0516300be79eb34cb38ad5bb422fec65b9bff885fe89e2fdfbae"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
