name = "FlywheelSMP"
author = "Kosmic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f19b1d7b5683238bd57ac778dd8af6bce03f127da6b77efe96374b3b6af8806a"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
