name = "FlywheelSeason2"
author = "Kosmic"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd339a5db0f3838a4f2932f641353d704079a2bb1506671149f58127e71773fa"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
